version: 2.1
orbs:
  node: circleci/node@3.0.0

executors:
  node14:
    docker:
      - image: circleci/node:14
    resource_class: small
    working_directory: ~/circle-sandbox

jobs:
  build:
    executor: node14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    parameters:
      browser:
        type: string
    executor: node14
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Demo param parsing
          command: |
            export BNAME=$(echo "<< parameters.browser >>" | awk '{print $NF}')
            export BVER=$(echo "<< parameters.browser >>" | awk 'NF{NF-=1}1')
            echo "Browser name: $BNAME"
            echo "Browser version: $BVER"
      - run:
          name: See if env vars pass between commands
          command: |
            echo "Browser name in later cmd: $BNAME"
            echo "Browser version in later cmd: $BVER"
      - run:
          name: Run tests
          command: npm test

workflows:
  node-tests:
    jobs:
      - build
      - test:
          browser: internet explorer 11
          requires:
            - build
