version: 2.1
orbs:
  node: circleci/node@3.0.0

executors:
  node14:
    docker:
      - image: circleci/node:14
    resource_class: small
    working_directory: ~/circle-sandbox

jobs:
  build:
    executor: node14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    parameters:
      browser:
        type: string
    executor: node14
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Demo param parsing
          command: |
            name=$(echo "<< parameters.browser >>" | awk 'NF{NF-=1}1')
            version=$(echo "<< parameters.browser >>" | awk '{print $NF}')

            if [ $version = latest ]; then
              version=""
            fi

            echo "Browser name: $name"
            echo "Browser version: $version"

            echo "Testing error control"
            false
            echo "Still continued despite an error"
      - run:
          name: Run tests
          command: npm test

workflows:
  node-tests:
    jobs:
      - build
      - test:
          requires:
            - build
          matrix:
            parameters:
              browser:
                - internet explorer 11
#                - internet explorer 10
#                - firefox latest
#                - firefox 78
#                - firefox 68
#                - chrome latest
#                - safari 14
#                - safari 13
#                - safari 12
#                - safari 11
#                - safari 10
#                - safari 9
#                - safari 8
#                - MicrosoftEdge latest
