version: 2.1
orbs:
  node: circleci/node@3.0.0

executors:
  node14:
    docker:
      - image: circleci/node:14
    resource_class: small
    working_directory: ~/circle-sandbox

jobs:
  build:
    executor: node14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor: node14
    steps:
      - attach_workspace:
          at: .
      - run:
          name: List files
          command: find . -print
      - run:
          name: Run tests
          command: npm test

workflows:
  node-tests:
    jobs:
      - build
      - test:
          requires:
            - build
